Minor updates and add local deployer
studio24/deployer-recipes pull request #5
Opened 2021-03-17 17:48 UTC by AlanJIsaacson

Added local deployer to avoid package version errors.
Update the documentation as needed.
Adjust show-summary method for reading the build information

2021-03-18 11:43 UTC, AlanJIsaacson reviewed
Those changes make sense to me and read well.

2021-03-18 15:25 UTC, simonrjones requested changes

2021-03-19 10:19 UTC, simonrjones commented on src/show-summary.php
> +    $file = $response->getContent();
I've edited this to make my suggested fix.

2021-03-19 10:22 UTC, simonrjones approved these changes

2021-03-19 10:22 UTC, merged